name: Build Homepage

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: code.mymiggi.de
          username: ${{ env.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            code.mymiggi.de/miggi/mymiggi-home-v2:dev-${{ env.GITHUB_RUN_NUMBER }}
            code.mymiggi.de/miggi/mymiggi-home-v2

      - name: Deploy via Portainer
        run: curl -v -X POST ${{ secrets.MYMIGGI_HOOK }}